In [108]:
import pandas as pd

In [109]:
df=pd.read_csv('../Desktop/Data.csv',low_memory=False)

In [110]:
df

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44591,3669,2010010308,NYJ,CIN,CIN,away,NYJ,NYJ,26.0,2010-01-03,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
44592,3704,2010010308,NYJ,CIN,NYJ,home,CIN,CIN,28.0,2010-01-03,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
44593,3725,2010010308,NYJ,CIN,NYJ,home,CIN,CIN,29.0,2010-01-03,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
44594,3747,2010010308,NYJ,CIN,NYJ,home,CIN,CIN,30.0,2010-01-03,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
44595,3768,2010010308,NYJ,CIN,NaN,NaN,NaN,CIN,NaN,2010-01-03,...,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
df.shape

(44596, 256)

In [112]:
df.isna().sum()

play_id                              0
game_id                              0
home_team                            0
away_team                            0
posteam                           1548
                                 ...
penalty_type                     41714
defensive_two_point_attempt       1512
defensive_two_point_conv          1512
defensive_extra_point_attempt     1512
defensive_extra_point_conv        1512
Length: 256, dtype: int64

In [113]:
#the sum of NaN value in DataFrame
df.isna().sum().sum()

4393294

In [114]:
col_number=len(list(df.columns))
col_number

256

In [115]:
row_number=len(list(df.index))
row_number

44596

In [116]:
df.head()

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,NaN,NaN,NaN,0,NaN,NaN,0.0,0.0,0.0,0.0

In [117]:
#find the percentage NAN in each column
def percnt_missing(df):
    percnt_missing_data =(df.isna().sum()*100/row_number)/100
    percentage_NAN_in_each_column=percnt_missing_data.to_dict()
    return percentage_NAN_in_each_column

In [118]:
percnt_missing(df)

{'play_id': 0.0,
 'game_id': 0.0,
 'home_team': 0.0,
 'away_team': 0.0,
 'posteam': 0.03471163333034353,
 'posteam_type': 0.03401650372230693,
 'defteam': 0.03401650372230693,
 'side_of_field': 0.0014799533590456543,
 'yardline_100': 0.03442012736568302,
 'game_date': 0.0,
 'quarter_seconds_remaining': 0.0004036236433760875,
 'half_seconds_remaining': 0.0004036236433760875,
 'game_seconds_remaining': 0.0004036236433760875,
 'game_half': 0.0,
 'quarter_end': 0.0,
 'drive': 0.0,
 'sp': 0.0,
 'qtr': 0.0,
 'down': 0.1529957843752803,
 'goal_to_go': 0.033724997757646424,
 'time': 0.0004036236433760875,
 'yrdln': 0.0014799533590456543,
 'ydstogo': 0.0,
 'ydsnet': 0.0,
 'desc': 0.0,
 'play_type': 0.033904386043591354,
 'yards_gained': 0.0,
 'shotgun': 0.0,
 'no_huddle': 0.0,
 'qb_dropback': 0.033904386043591354,
 'qb_kneel': 0.0,
 'qb_spike': 0.0,
 'qb_scramble': 0.0,
 'pass_length': 0.6215579872634317,
 'pass_location': 0.6215579872634317,
 'air_yards': 0.61830657458068,
 'yards_after_catch': 0.7675352049511167,
 'run_location': 0.6951520315723383,
 'run_gap': 0.7801372320387479,
 'field_goal_result': 0.9791461117589022,
 'kick_distance': 0.8703695398690465,
 'extra_point_result': 0.9753341106825724,
 'two_point_conv_result': 0.9987667055341286,
 'home_timeouts_remaining': 0.0,
 'away_timeouts_remaining': 0.0,
 'timeout': 0.033904386043591354,
 'timeout_team': 0.9587182706969234,
 'td_team': 0.9720378509283344,
 'posteam_timeouts_remaining': 0.03401650372230693,
 'defteam_timeouts_remaining': 0.03401650372230693,
 'total_home_score': 0.0,
 'total_away_score': 0.0,
 'posteam_score': 0.039756928872544624,
 'defteam_score': 0.039756928872544624,
 'score_differential': 0.039756928872544624,
 'posteam_score_post': 0.03401650372230693,
 'defteam_score_post': 0.03401650372230693,
 'score_differential_post': 0.03401650372230693,
 'no_score_prob': 0.0010763297156695668,
 'opp_fg_prob': 0.0010763297156695668,
 'opp_safety_prob': 0.0010763297156695668,
 'opp_td_prob': 0.0010763297156695668,
 'fg_prob': 0.0010763297156695668,
 'safety_prob': 0.0010763297156695668,
 'td_prob': 0.0010763297156695668,
 'extra_point_prob': 0.0,
 'two_point_conversion_prob': 0.0,
 'ep': 0.03498071575926092,
 'epa': 0.04029509373037941,
 'total_home_epa': 0.0,
 'total_away_epa': 0.0,
 'total_home_rush_epa': 0.0,
 'total_away_rush_epa': 0.0,
 'total_home_pass_epa': 0.0,
 'total_away_pass_epa': 0.0,
 'air_epa': 0.622589469907615,
 'yac_epa': 0.6235761054803121,
 'comp_air_epa': 0.03415104493676563,
 'comp_yac_epa': 0.03457709211588483,
 'total_home_comp_air_epa': 0.0,
 'total_away_comp_air_epa': 0.0,
 'total_home_comp_yac_epa': 0.0,
 'total_away_comp_yac_epa': 0.0,
 'total_home_raw_air_epa': 0.0,
 'total_away_raw_air_epa': 0.0,
 'total_home_raw_yac_epa': 0.0,
 'total_away_raw_yac_epa': 0.0,
 'wp': 0.04081083505247108,
 'def_wp': 0.04081083505247108,
 'home_wp': 0.03598977486770114,
 'away_wp': 0.03598977486770114,
 'wpa': 0.011234191407301104,
 'home_wp_post': 0.04025024665889317,
 'away_wp_post': 0.04025024665889317,
 'total_home_rush_wpa': 0.0,
 'total_away_rush_wpa': 0.0,
 'total_home_pass_wpa': 0.0,
 'total_away_pass_wpa': 0.0,
 'air_wpa': 0.6228361288007893,
 'yac_wpa': 0.6234639878015965,
 'comp_air_wpa': 0.0343977038299399,
 'comp_yac_wpa': 0.03468920979460041,
 'total_home_comp_air_wpa': 0.0,
 'total_away_comp_air_wpa': 0.0,
 'total_home_comp_yac_wpa': 0.0,
 'total_away_comp_yac_wpa': 0.0,
 'total_home_raw_air_wpa': 0.0,
 'total_away_raw_air_wpa': 0.0,
 'total_home_raw_yac_wpa': 0.0,
 'total_away_raw_yac_wpa': 0.0,
 'punt_blocked': 0.033904386043591354,
 'first_down_rush': 0.033904386043591354,
 'first_down_pass': 0.033904386043591354,
 'first_down_penalty': 0.033904386043591354,
 'third_down_converted': 0.033904386043591354,
 'third_down_failed': 0.033904386043591354,
 'fourth_down_converted': 0.033904386043591354,
 'fourth_down_failed': 0.033904386043591354,
 'incomplete_pass': 0.033904386043591354,
 'touchback': 0.0,
 'interception': 0.033904386043591354,
 'punt_inside_twenty': 0.033904386043591354,
 'punt_in_endzone': 0.033904386043591354,
 'punt_out_of_bounds': 0.033904386043591354,
 'punt_downed': 0.033904386043591354,
 'punt_fair_catch': 0.033904386043591354,
 'kickoff_inside_twenty': 0.033904386043591354,
 'kickoff_in_endzone': 0.033904386043591354,
 'kickoff_out_of_bounds': 0.033904386043591354,
 'kickoff_downed': 0.033904386043591354,
 'kickoff_fair_catch': 0.033904386043591354,
 'fumble_forced': 0.033904386043591354,
 'fumble_not_forced': 0.033904386043591354,
 'fumble_out_of_bounds': 0.033904386043591354,
 'solo_tackle': 0.033904386043591354,
 'safety': 0.033904386043591354,
 'penalty': 0.033904386043591354,
 'tackled_for_loss': 0.033904386043591354,
 'fumble_lost': 0.033904386043591354,
 'own_kickoff_recovery': 0.033904386043591354,
 'own_kickoff_recovery_td': 0.033904386043591354,
 'qb_hit': 0.033904386043591354,
 'rush_attempt': 0.033904386043591354,
 'pass_attempt': 0.033904386043591354,
 'sack': 0.033904386043591354,
 'touchdown': 0.033904386043591354,
 'pass_touchdown': 0.033904386043591354,
 'rush_touchdown': 0.033904386043591354,
 'return_touchdown': 0.033904386043591354,
 'extra_point_attempt': 0.033904386043591354,
 'two_point_attempt': 0.033904386043591354,
 'field_goal_attempt': 0.033904386043591354,
 'kickoff_attempt': 0.033904386043591354,
 'punt_attempt': 0.033904386043591354,
 'fumble': 0.033904386043591354,
 'complete_pass': 0.033904386043591354,
 'assist_tackle': 0.033904386043591354,
 'lateral_reception': 0.033904386043591354,
 'lateral_rush': 0.033904386043591354,
 'lateral_return': 0.033904386043591354,
 'lateral_recovery': 0.033904386043591354,
 'passer_player_id': 0.5923849672616378,
 'passer_player_name': 0.5923849672616378,
 'receiver_player_id': 0.6221409991927527,
 'receiver_player_name': 0.6222979639429546,
 'rusher_player_id': 0.6837384518790922,
 'rusher_player_name': 0.6837608754148354,
 'lateral_receiver_player_id': 0.9997533411068257,
 'lateral_receiver_player_name': 0.9997533411068257,
 'lateral_rusher_player_id': 1.0,
 'lateral_rusher_player_name': 1.0,
 'lateral_sack_player_id': 1.0,
 'lateral_sack_player_name': 1.0,
 'interception_player_id': 0.988227643734864,
 'interception_player_name': 0.988227643734864,
 'lateral_interception_player_id': 0.9998654587855412,
 'lateral_interception_player_name': 0.9998654587855412,
 'punt_returner_player_id': 0.9617902950937304,
 'punt_returner_player_name': 0.9618127186294736,
 'lateral_punt_returner_player_id': 0.9999103058570276,
 'lateral_punt_returner_player_name': 0.9999103058570276,
 'kickoff_returner_player_name': 0.9547268813346489,
 'kickoff_returner_player_id': 0.9547044577989057,
 'lateral_kickoff_returner_player_id': 0.9999103058570276,
 'lateral_kickoff_returner_player_name': 0.9999103058570276,
 'punter_player_id': 0.9451744551080814,
 'punter_player_name': 0.9451744551080814,
 'kicker_player_name': 0.8987801596555746,
 'kicker_player_id': 0.8987801596555746,
 'own_kickoff_recovery_player_id': 0.9997757646425689,
 'own_kickoff_recovery_player_name': 0.9997757646425689,
 'blocked_player_id': 0.9991030585702754,
 'blocked_player_name': 0.9991030585702754,
 'tackle_for_loss_1_player_id': 0.9468337967530721,
 'tackle_for_loss_1_player_name': 0.9468337967530721,
 'tackle_for_loss_2_player_id': 1.0,
 'tackle_for_loss_2_player_name': 1.0,
 'qb_hit_1_player_id': 0.9496815857924478,
 'qb_hit_1_player_name': 0.9496815857924478,
 'qb_hit_2_player_id': 0.9982958112835232,
 'qb_hit_2_player_name': 0.9982958112835232,
 'forced_fumble_player_1_team': 0.9889003498071576,
 'forced_fumble_player_1_player_id': 0.9889003498071576,
 'forced_fumble_player_1_player_name': 0.9889003498071576,
 'forced_fumble_player_2_team': 0.9998878823212844,
 'forced_fumble_player_2_player_id': 0.9998878823212844,
 'forced_fumble_player_2_player_name': 0.9999103058570276,
 'solo_tackle_1_team': 0.5291281729303077,
 'solo_tackle_2_team': 0.9931832451340928,
 'solo_tackle_1_player_id': 0.5291281729303077,
 'solo_tackle_2_player_id': 0.9931832451340928,
 'solo_tackle_1_player_name': 0.5291281729303077,
 'solo_tackle_2_player_name': 0.9932056686698358,
 'assist_tackle_1_player_id': 0.8622297963942954,
 'assist_tackle_1_player_name': 0.8622297963942954,
 'assist_tackle_1_team': 0.8622297963942954,
 'assist_tackle_2_player_id': 0.8622522199300385,
 'assist_tackle_2_player_name': 0.8622522199300385,
 'assist_tackle_2_team': 0.8622522199300385,
 'assist_tackle_3_player_id': 1.0,
 'assist_tackle_3_player_name': 1.0,
 'assist_tackle_3_team': 1.0,
 'assist_tackle_4_player_id': 1.0,
 'assist_tackle_4_player_name': 1.0,
 'assist_tackle_4_team': 1.0,
 'pass_defense_1_player_id': 0.947573773432595,
 'pass_defense_1_player_name': 0.947573773432595,
 'pass_defense_2_player_id': 0.9985648937124405,
 'pass_defense_2_player_name': 0.9985648937124405,
 'fumbled_1_team': 0.9835187012288098,
 'fumbled_1_player_id': 0.9835187012288098,
 'fumbled_1_player_name': 0.9835187012288098,
 'fumbled_2_player_id': 0.9998878823212844,
 'fumbled_2_player_name': 0.9998878823212844,
 'fumbled_2_team': 0.9998878823212844,
 'fumble_recovery_1_team': 0.9850210781235985,
 'fumble_recovery_1_yards': 0.9850210781235985,
 'fumble_recovery_1_player_id': 0.9850210781235985,
 'fumble_recovery_1_player_name': 0.9850659251950847,
 'fumble_recovery_2_team': 0.9998654587855412,
 'fumble_recovery_2_yards': 0.9998654587855412,
 'fumble_recovery_2_player_id': 0.9998654587855412,
 'fumble_recovery_2_player_name': 0.9998878823212844,
 'return_team': 0.9166068705713516,
 'return_yards': 0.0,
 'penalty_team': 0.932123957305588,
 'penalty_player_id': 0.932123957305588,
 'penalty_player_name': 0.9349044757377344,
 'penalty_yards': 0.932123957305588,
 'replay_or_challenge': 0.0,
 'replay_or_challenge_result': 0.9932505157413221,
 'penalty_type': 0.9353753699883397,
 'defensive_two_point_attempt': 0.033904386043591354,
 'defensive_two_point_conv': 0.033904386043591354,
 'defensive_extra_point_attempt': 0.033904386043591354,
 'defensive_extra_point_conv': 0.033904386043591354}

In [119]:
#numbers of columns have missing data
def colunm_missing(df):
    percentage_NAN_in_each_column=percnt_missing(df)
    count_NaN=0
    for index in df:
        if percentage_NAN_in_each_column[index]>0:
            count_NaN+=1        
    print("The number of columns that contain NAN :",count_NaN)
colunm_missing(df)

The number of columns that contain NAN : 202

In [120]:
# Delete columns which contain more than 50% of NaN values
def cleanBigNaN(df,percnt_missing):
    number_valid =  int(((100-percnt_missing)/100)*row_number + 1)
    df.dropna( axis=1, thresh=number_valid,inplace=True)
    return df
df = cleanBigNaN(df,50)
df.shape

(44596, 151)

In [121]:
colunm_missing(df)

The number of columns that contain NAN : 97

In [122]:
#fill missing values by global constant(((numbers = 999 & string = Missing)))
#after I understand that the data frame has an identifier feature, so I run this code before filling in the interpolation
df= df.fillna({'posteam':'Missing',
                   'posteam_type':'Missing',
                   'defteam':'Missing',
                  'side_of_field':'Missing',
                   'time':999,
                  'yrdln':'Missing',
                   'play_type':'Missing',
                   'pass_length':'Missing',
                   'pass_location':'Missing',
                  'run_location':'Missing',
                   'passer_player_id':999,
                   'passer_player_name':'Missing',
                   'receiver_player_id':999,
                   'receiver_player_name':'Missing',
                   'rusher_player_id':999,
                   'rusher_player_name':'Missing',
                   'solo_tackle_1_team':'Missing',
                   'solo_tackle_1_player_id':999,
                   'solo_tackle_1_player_name':'Missing',
                  })

In [123]:
colunm_missing(df)

The number of columns that contain NAN : 90

In [124]:
#fill missing values by interpolate
df=df.interpolate(method='linear')

In [125]:
colunm_missing(df)

The number of columns that contain NAN : 11

In [126]:
#to show 18 columns that contain nan
my_df=df[df.columns[df.isna().any()]]
my_df.head(10)

,down,posteam_score,defteam_score,score_differential,wp,def_wp,home_wp,away_wp,wpa,home_wp_post,away_wp_post
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,0.0,0.0,0.0,0.546433,0.453567,0.546433,0.453567,0.004655,0.551088,0.448912
2,2.0,0.0,0.0,0.0,0.551088,0.448912,0.551088,0.448912,-0.040295,0.510793,0.489207
3,3.0,0.0,0.0,0.0,0.510793,0.489207,0.510793,0.489207,-0.049576,0.461217,0.538783
4,4.0,0.0,0.0,0.0,0.461217,0.538783,0.461217,0.538783,0.097712,0.558929,0.441071
5,1.0,0.0,0.0,0.0,0.441071,0.558929,0.558929,0.441071,-0.019524,0.578453,0.421547
6,2.0,0.0,0.0,0.0,0.421547,0.578453,0.578453,0.421547,-0.004427,0.582881,0.417119
7,3.0,0.0,0.0,0.0,0.417119,0.582881,0.582881,0.417119,-0.034663,0.617544,0.382456
8,4.0,0.0,0.0,0.0,0.382456,0.617544,0.617544,0.382456,0.026054,0.591489,0.408511
9,1.0,0.0,0.0,0.0,0.591489,0.408511,0.591489,0.408511,-0.006084,0.585405,0.414595

In [127]:
df[df.columns[df.isna().any()]].isna().sum()

down                  1
posteam_score         1
defteam_score         1
score_differential    1
wp                    1
def_wp                1
home_wp               1
away_wp               1
wpa                   1
home_wp_post          1
away_wp_post          1
dtype: int64

In [128]:
#fill missing values numraic by mean
df=df.fillna(value=df[['wp','away_wp_post','home_wp_post','wpa','away_wp','home_wp','down','def_wp']].mean())

In [129]:
colunm_missing(df)

The number of columns that contain NAN : 3

In [130]:
# Fill in missing values for features that have the same (majority) value in them
df[['posteam_score','defteam_score','score_differential']] =  df[['posteam_score','defteam_score','score_differential']].fillna(0)
df

,play_id,game_id,home_team,away_team,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,...,lateral_reception,lateral_rush,lateral_return,lateral_recovery,return_yards,replay_or_challenge,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv
0,46,2009091000,PIT,TEN,PIT,home,TEN,TEN,30.0,2009-09-10,...,0.0,0.0,0.0,0.0,39,0,0.0,0.0,0.0,0.0
1,68,2009091000,PIT,TEN,PIT,home,TEN,PIT,58.0,2009-09-10,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
2,92,2009091000,PIT,TEN,PIT,home,TEN,PIT,53.0,2009-09-10,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
3,113,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
4,139,2009091000,PIT,TEN,PIT,home,TEN,PIT,56.0,2009-09-10,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44591,3669,2010010308,NYJ,CIN,CIN,away,NYJ,NYJ,26.0,2010-01-03,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
44592,3704,2010010308,NYJ,CIN,NYJ,home,CIN,CIN,28.0,2010-01-03,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
44593,3725,2010010308,NYJ,CIN,NYJ,home,CIN,CIN,29.0,2010-01-03,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
44594,3747,2010010308,NYJ,CIN,NYJ,home,CIN,CIN,30.0,2010-01-03,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0
44595,3768,2010010308,NYJ,CIN,Missing,Missing,Missing,CIN,30.0,2010-01-03,...,0.0,0.0,0.0,0.0,0,0,0.0,0.0,0.0,0.0

In [131]:
colunm_missing(df)

The number of columns that contain NAN : 0

In [132]:
df.isna().sum().sum()

0